services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    restart: always


  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: airflow-custom:latest
    ports:
      - "8080:8080"
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: supersecretkey123
    volumes:
      - ./dags:/opt/airflow/dags
      - ../models:/opt/airflow/models
      - ../src:/opt/airflow/src 
    command: standalone


  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    image: airflow-custom:latest
    depends_on:
      - airflow-webserver
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: supersecretkey123
    volumes:
      - ./dags:/opt/airflow/dags
      - ../models:/opt/airflow/models
      - ../src:/opt/airflow/src 
    command: scheduler

volumes:
  postgres-db-volume: